#!/usr/bin/env bash
# Build, stage, and deploy a ProxiPort demo to an existing Linux host.
#
# Builds proxiportd (linux/amd64) and the SvelteKit SPA from the local
# tree, scp's them to the remote host, then runs deploy/server/install.sh
# remotely. Idempotent — re-running redeploys the latest local code.
#
# Required env:
#   HOST          public hostname the demo will serve at (e.g. demo.proxiport.net)
#   EMAIL         contact email for Let's Encrypt
#   SSH_TARGET    ssh login string (e.g. root@demo.proxiport.net)
#
# Optional env:
#   SSH_KEY       path to private key for SSH (passed to ssh -i / scp -i)
#   STAGE_DIR     local stage dir (default: ./build/demo-stage)
#   REMOTE_STAGE  remote stage dir (default: /tmp/proxiport-demo)
#   SKIP_BUILD    if non-empty, reuse existing artefacts under STAGE_DIR
#   DRY_RUN       if non-empty, print what would happen and exit before
#                 any remote action (local build still runs unless SKIP_BUILD)
set -euo pipefail

: "${HOST:?HOST=public.hostname required}"
: "${EMAIL:?EMAIL=contact@example.com required}"
: "${SSH_TARGET:?SSH_TARGET=user@host required}"

STAGE_DIR="${STAGE_DIR:-$(pwd)/build/demo-stage}"
REMOTE_STAGE="${REMOTE_STAGE:-/tmp/proxiport-demo}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SSH_OPTS=()
if [[ -n "${SSH_KEY:-}" ]]; then
    SSH_OPTS+=(-i "$SSH_KEY")
fi

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
run() {
    if [[ -n "${DRY_RUN:-}" ]]; then
        printf '   [dry-run] %s\n' "$*"
    else
        eval "$@"
    fi
}

if [[ -z "${SKIP_BUILD:-}" ]]; then
    say "Building proxiportd (linux/amd64, CGO=1)"
    mkdir -p "$STAGE_DIR"
    (
        cd "$REPO_ROOT"
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -ldflags "-s -w" \
            -o "$STAGE_DIR/proxiportd" ./cmd/proxiportd
    )

    say "Building SvelteKit SPA"
    (
        cd "$REPO_ROOT/frontend"
        npm ci --no-audit --no-fund
        npm run build
    )
    rm -rf "$STAGE_DIR/spa"
    mkdir -p "$STAGE_DIR/spa"
    cp -a "$REPO_ROOT/frontend/build/." "$STAGE_DIR/spa/"
else
    say "SKIP_BUILD set — reusing $STAGE_DIR"
fi

say "Rendering proxiportd.conf for $HOST"
KEY_SEED="$(openssl rand -hex 18)"
ADMIN_PW="$(openssl rand -base64 24 | tr -d '+/=' | cut -c1-24)"
CLIENT_AUTH_PW="$(openssl rand -base64 24 | tr -d '+/=' | cut -c1-24)"
JWT_SECRET="$(openssl rand -hex 32)"

sed \
    -e "s|__HOST__|$HOST|g" \
    -e "s|__KEY_SEED__|$KEY_SEED|g" \
    -e "s|__ADMIN_PW__|$ADMIN_PW|g" \
    -e "s|__CLIENT_AUTH_PW__|$CLIENT_AUTH_PW|g" \
    -e "s|__JWT_SECRET__|$JWT_SECRET|g" \
    "$SCRIPT_DIR/proxiportd.conf.template" > "$STAGE_DIR/proxiportd.conf"
cp "$REPO_ROOT/deploy/server/proxiportd.service" "$STAGE_DIR/proxiportd.service"

cat > "$STAGE_DIR/.demo-credentials" <<EOF
# Generated by deploy/demo/deploy.sh on $(date -u +%FT%TZ)
# Keep these out of any committed file. The demo host re-reads them
# from /etc/proxiport/proxiportd.conf on systemd start.
admin user        admin
admin password    $ADMIN_PW
client auth user  smoketest
client auth pw    $CLIENT_AUTH_PW
EOF
chmod 0600 "$STAGE_DIR/.demo-credentials"
say "Credentials written to $STAGE_DIR/.demo-credentials (mode 0600)"

if [[ -n "${DRY_RUN:-}" ]]; then
    say "DRY_RUN set — stopping before remote actions"
    echo
    echo "Would scp these to $SSH_TARGET:$REMOTE_STAGE/ :"
    ls -lh "$STAGE_DIR" | sed 's|^|    |'
    echo
    echo "Would then ssh and run:"
    echo "    cd $REMOTE_STAGE && \\"
    echo "      sudo HOST=$HOST EMAIL=$EMAIL STAGE=$REMOTE_STAGE \\"
    echo "      bash $REMOTE_STAGE/install.sh"
    echo "    sudo install -d -o proxiport -g proxiport -m 0750 /var/lib/proxiport/docroot"
    echo "    sudo rsync -a $REMOTE_STAGE/spa/ /var/lib/proxiport/docroot/"
    echo "    sudo chown -R proxiport:proxiport /var/lib/proxiport/docroot"
    echo "    sudo systemctl restart proxiportd"
    exit 0
fi

say "Staging to $SSH_TARGET:$REMOTE_STAGE"
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p $REMOTE_STAGE"
scp "${SSH_OPTS[@]}" \
    "$STAGE_DIR/proxiportd" \
    "$STAGE_DIR/proxiportd.conf" \
    "$STAGE_DIR/proxiportd.service" \
    "$REPO_ROOT/deploy/server/install.sh" \
    "$SSH_TARGET:$REMOTE_STAGE/"
scp -r "${SSH_OPTS[@]}" "$STAGE_DIR/spa" "$SSH_TARGET:$REMOTE_STAGE/spa"

say "Running install.sh remotely"
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "
    set -euo pipefail
    cd $REMOTE_STAGE
    sudo HOST=$HOST EMAIL=$EMAIL STAGE=$REMOTE_STAGE bash $REMOTE_STAGE/install.sh
    sudo install -d -o proxiport -g proxiport -m 0750 /var/lib/proxiport/docroot
    sudo rsync -a --delete $REMOTE_STAGE/spa/ /var/lib/proxiport/docroot/
    sudo chown -R proxiport:proxiport /var/lib/proxiport/docroot
    sudo systemctl restart proxiportd
    sleep 2
    sudo systemctl --no-pager --full status proxiportd | head -20
"

say "Done. Demo live at https://$HOST/"
say "Credentials stashed at $STAGE_DIR/.demo-credentials (not pushed to git)"
